freshr:
  utils:
    encrypt-salt: ENCRYPT-GATEWAY
    jwt-salt: JWT-GATEWAY
  entity:
    rsa-ttl: 300
    access-ttl: 15552000
    refresh-ttl: 15552000
    access-expiration: 900

spring:
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        SQL: trace
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379
      password: redis-password

  elasticsearch:
    uris: http://localhost:9200
    password: elasticsearch-password

logging:
  level:
    root: info
